ecommerce_project/cart_app/urls.py
from django.urls import path
from . import views

app_name='cart_app'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),


]

ecommerce_project/ecommerce_app/urls.py
from django.urls import path
from . import views
app_name='ecommerce_app'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail')
]

ecommerce_project/ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce_app/',include('ecommerce_app.urls')),
    path('search/',include('search_App.urls')),
    path('cart_app',include('cart_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce_project/search_App/urls.py
from django.urls import path
from . import views

app_name='search_App'
urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

ecommerce_project/cart_app/models.py
from django.db import models
from ecommerce_app.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce_project/ecommerce_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    imge=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('ecommerce_app:product_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
        name=models.CharField(max_length=250,unique=True)
        slug=models.SlugField(max_length=250,unique=True)
        description=models.TextField(blank=True)
        price=models.DecimalField(max_digits=10,decimal_places=2)
        category=models.ForeignKey('Category',on_delete=models.CASCADE)
        imge=models.ImageField(upload_to='product',blank=True)
        stock=models.IntegerField()
        available=models.BooleanField(default=True)
        created=models.DateTimeField(auto_now_add=True)
        updated=models.DateTimeField(auto_now=True)
        def get_url(self):
            return reverse('ecommerce_app:prodCatdetail',args=[self.category.slug,self.slug])


        class Meta:
            ordering=('name',)
            verbose_name='product'
            verbose_name_plural='products'

        def __str__(self):
            return '{}'.format(self.name)

ecommerce_project/search_App/models.py
from django.db import models

# Create your models here.

ecommerce_project/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerce_app.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        print('not cart')
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product, id=product_id)
    cart_item=CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

ecommerce_project/ecommerce_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.
#
# def index(request):
#     return HttpResponse("hey am here")

def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug !=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:

        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try :
        page=int(request.GET.get('page','1'))
    except :
        page=1
    try :
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category': c_page, 'products': products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerce_project/search_App/views.py
from django.shortcuts import render
from ecommerce_app.models import Product
from django.db.models import Q

# Create your views here.
def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

ecommerce_project/ecommerce_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
     <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta  name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
    <div>
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>

        {% include 'footer.html' %}

        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

ecommerce_project/ecommerce_app/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is your Cart page. Proceed to review your items and place the order
{% endblock %}
{% block title %}
      Cart -Shopie Company pvt ltd
{% endblock %}
{% block content %}
    {% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                YourShopping Cart is empty
            </h1>
            <br>
            <p class="text-center">
                Please Click <a href="{% url 'ecommerce_app:allProdCat' %}">Here</a> to continue shopping.
            </p>
        </div>
    </div>
    {% else %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_titile">
                Your Shopping Cart
            </h1>
            <br>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                    <tr>
                        <th colspan="5">
                            Your Items
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.imge.url}}" alt="" style="with:50px; height:100px;" class="float-left rounded custom_imge"></a>
                        </td>
                        <td class="text-lef">
                            {{cart_item.product.name}}
                            <br>
                            SKU: {{cart_item.product.id}}
                            <br>
                            Price: $ {{cart_item.product.price}}
                            <br>
                             QTV: {{cart_item.quantity}} x $ {{cart_item.product.price}}
                        </td>
                        <td>
                            $ {{cart_item.sub_total}}
                        </td>
                        {% if cart_item.quantity < cart_item.product.stock %}
                        <td>
                            <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus-circle custom_icon"> </i></a>
                            &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-minus-circle custom_icon"> </i></a>
                            &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa fa-trash custom_icon"> </i></a>
                        </td>
                        {% else %}
                         <td>
                            &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa fa-minus-circle custom_icon"></i></a>
                            &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa fa-trash custom_icon"></i></a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th>Checkout</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        Please review youe shopping cart items before proceeding with the order payment.
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your total is : <strong>{{ total }}</strong>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'ecommerce_app:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
            </div>
            <div class="btn btn-secondary btn-block my_custom_button">Continue to Payment</div>
        </div>
    </div>
    </div>
    {% endif %}

{% endblock %}

ecommerce_project/ecommerce_app/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:160 }}
    {% else %}
        Welcome to Shopie Store where you can buy different items...
    {% endif %}
{% endblock %}

    {% block title %}
    {% if category %}
        {{ category.name }} - Shopie Store
    {% else %}
        See our new collections -Shopie Store
    {% endif %}
    {% endblock %}

{% block content %}
{% if category %}

    <div>
        <div class="row my_row_class">
            <div class="mx_auto">
            <p><a href="{% url 'ecommerce_app:allProdCat' %}"> Our Product Collection</a>{{category.name}}</p>
            </div>
        </div>
    </div>


<div>
{% endif %}
    <div class="mx_auto">
    {% if category %}
        <img class="my_image" src="{{category.imge.url}}" alt="{{category.name}}">
    </div>
</div>
<br>
    <div>
    <h1 class="text-centre my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
    </div>
{% else %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="our products", width="1500px";, height="450px";>
</div>
<br>
<div>
    <h1 class="text-centre my_title">See More Collections</h1>
    <p class="text-justify">See more ideas about mens outfits, men casual, mens fashion casual. ... Formal Dresses For Men, Formal Men Outfit, Casual Wear For Men, Men Formal.</p>
</div>
{% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card-text-center" style="min-width:18rem;, height:450px;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" style="width:350px; height:450px;" src="{{product.imge.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecommerce_project/ecommerce_app/templates/footer.html
<footer class="mt-auto">
  <div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;SHOPIE Tech pvt ltd.All rights Reserved</p>
  </div>
</footer>

ecommerce_project/ecommerce_app/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'ecommerce_app:allProdCat' %}"></a><img src="{% static 'img/log.png' %}" alt="logimge" width="150px;",height="200px;">
  </center>
</header>

ecommerce_project/ecommerce_app/templates/navbar.html
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item">
         <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'ecommerce_app' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ecommerce_app:allProdCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart_app:cart_detail' %}"><i class="fa fa-shopping-cart">({{item_count}})</i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_App:searchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce_project/ecommerce_app/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.description|truncatewords:160 }}

    {% endblock %}
    {% block title %}
    {% if category %}
        {{ product.name }} - Shopie Store

    {% endif %}
    {% endblock %}

{% block content %}
<div class="row my_product_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'ecommerce_app:allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.imge.url}}" alt="{{product.name}}">

        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_product_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' product.id %}">Add to Cart</a>
            {% endif %}
            </div>
        </div>
</div>
</div>

{% endblock %}

ecommerce_project/ecommerce_app/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        We have variety of Collections
{% endblock %}
{% block title %}
      Search
{% endblock %}
{% block content %}
<div>
        <p class="text-center my_search_text">You have searched for :<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card-text-center" style="min-width:18rem;, height:450px;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.imge.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>
                    </div>
            </div>
        </div>
        {% empty %}
        <div class="row max-auto">
            <p class="text-center my_search_text"> 0 results found </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}